FROM python:3.10-slim as base

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ENV PORT=${PORT:-8080}
ENV WORKERS=3

WORKDIR /app
COPY requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt

COPY src /app/src

CMD ["sh", "-c", "uvicorn --host 0.0.0.0 --port $PORT --workers $WORKERS --log-level info src.sandbox_local:app"]
