name: Bugfix (Don't use this unless you want to change our repository. Sweep runs in your own repository)
title: 'Sweep: '
description: Write something like "We notice ... behavior when ... happens instead of ...""
labels: sweep
body:
  - type: textarea
    id: description
    attributes:
      label: Details
      description: More details about the bug
      placeholder: "The bug might be in ... file. Here are the logs: ..."
