name: Bugfix
title: 'Sweep: '
description: Write something like "We notice ... behavior when ... happens instead of ...""
labels: sweep
body:
  - type: textarea
    id: description
    attributes:
      label: Details
      description: More details about the bug
      placeholder: The bug might be in ... file
  - type: textarea
    id: write
    attributes:
      label: Files to change
      description: Full file paths, one per line. Sweep can guess these files but including it can improve Sweep's results.
      render: shell
  - type: textarea
    id: read
    attributes:
      label: Files to read
      description: Full file paths, one per line. Sweep can guess these files but including it can improve Sweep's results.
      render: shell
