name: Bugfix
title: 'Sweep: '
description: Write something like "We notice ... behavior when ... happens instead of ...""
labels: sweep
body:
  - type: textarea
    id: description
    attributes:
      label: Details
      description: More details about the bug
      placeholder: The bug might be in ... file. Here are the logs: ...
  - type: textarea
    id: write
    attributes:
      label: Files to change
      description: Optional but can improve Sweep
      placeholder: "src/main.py\ntests/test.py"
      render: shell
