name: Feature Request
title: 'Sweep: '
description: Write something like "Write an api endpoint that does "..." in the "..." file"
labels: sweep
body:
  - type: textarea
    id: description
    attributes:
      label: Details
      description: More details for Sweep
      placeholder: The new endpoint should use the ... class from ... file because it contains ... logic.
  - type: textarea
    id: write
    attributes:
      label: Files to change (optional)
      description: Sweep can guess these files but including it can improve Sweep's performance
      placeholder: "src/main.py\ntests/test.py"
      render: shell
