name: Feature Request - What feature should Sweep handle?
title: 'Sweep: '
description: Write an api endpoint that does "..." in the "..." file
labels: sweep
body:
  - type: textarea
    id: description
    attributes:
      label: Details
      description: More details for Sweep
      placeholder: The new endpoint should use the ... class from ... file because it contains ... logic.