name: Refactor - What refactor should Sweep handle?
title: 'Sweep: '
description: "Modify the ... api endpoint to use ... version and ... framework"
labels: sweep
body:
  - type: textarea
    id: description
    attributes:
      label: Details
      description: More details for Sweep
      placeholder: We are migrating this function because ...