name: Refactor
title: 'Sweep: '
description: Write something like "Modify the ... api endpoint to use ... version and ... framework"
labels: sweep
body:
  - type: textarea
    id: description
    attributes:
      label: Details
      description: More details for Sweep
      placeholder: We are migrating this function to ... version because ...
  - type: textarea
    id: write
    attributes:
      label: Files to change
      description: Optional but can improve Sweep
      placeholder: "src/main.py\ntests/test.py"
      render: shell
