name: Test Install Script

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node: [18, 20, 21]
        shell: [bash, zsh]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: ${{ matrix.shell }} ./bin/install-assistant.sh
