name: JavaScript Linter

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    if: github.event.pull_request.merged == true && github.event.pull_request.title == 'Enable Github Actions'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: |
        npm ci
        npm install eslint --save-dev
    - name: Run ESLint
      run: |
        npx eslint .