name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install pytest
      run: |
        pip install pytest
    - name: Get new files
      id: getfiles
      run: |
        echo "::set-output name=files::$(git diff --name-only HEAD HEAD~1)"
    - name: Run pytest on new files
      run: |
        for file in ${{ steps.getfiles.outputs.files }}
        do
          if [[ $file == *.py ]]
          then
            pytest $file
          fi
        done
    - name: Test with pytest
      run: |
        pytest
