name: Python Linter

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    if: github.event.pull_request.merged == true && github.event.pull_request.title == 'Enable Github Actions'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint black
    - name: Run Black
      run: |
        black --check .
    - name: Run Pylint
      run: |
        pylint `ls -R|grep .py$|xargs`